### ISSUE TITLE
MIT license not recognised

### ISSUE THREAD

**Issue by rishikeshsjoshi** [awegroup/AWE-Power#15]
The license is not recognized by GitHub probably due to the added text. What will be a solution for this?

**Comment by edvinskis** [comment]
Hi Rishi,
 
Yes, typically when GitHub doesn't recognize the modified license, it means that the changes to the original license text are substantial enough that GitHub's automated tools can't match it to their database. Shortening the text is not an option because there's really nothing to shorten.

The TU Delft guidelines do not explicitly state that it has to be embedded in the license; they specify that it must be indicated in the license.
 
What you could do is:

1) Add a WAIVER in a separate file, that would look like this:

`WAIVER`
 
```
Technische Universiteit Delft hereby disclaims all copyright interest in the program “FixedWingGG-Power” (a fast cycle-power computation model) written by the Author(s).
 
dr. H.G.C. Henri Werij, Dean of Aerospace Engineering

Copyright (c) 2024 Rishikesh Joshi.
```
If you choose this option, also mention in the README that there is a waiver.

**or**

2) Add the waiver directly to the repository README ([example](https://gitlab.tudelft.nl/J.Iori/shipp)).

This way the original license will remain intact for recognition purposes.

**Comment by rschmehl** [comment]
Our Dean  should be listed as 
```
Prof.dr. H.G.C. (Henri) Werij
```
